branches:
  only:
    - binaries

install:
  - ps: Start-FileDownload 'http://leafo.net/dump/lua5_1_4_Win32_dll8_lib.zip'
  - ps: Start-FileDownload 'http://leafo.net/dump/lua5_1_4_Win32_bin.zip'
  - 7z x lua5_1_4_Win32_dll8_lib.zip
  - 7z x lua5_1_4_Win32_bin.zip -aos
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - dir .

build_script:
  - make

test_script:
  - moon.exe test.moon
  - moonc.exe test.moon
  - lua5.1.exe -e "assert(require('moonscript')); print(require('moonscript.version').version)"

after_build:
  - 7z a build.zip moonscript.dll lua51.dll moon.exe moonc.exe LICENSE README.txt

artifacts:
  - path: build.zip

deploy:
  - provider: GitHub
    artifact: build.zip
    draft: false
    prerelease: false
    on:
      branch: binaries
      appveyor_repo_tag: true
