branches:
  only:
    - binaries

install:
  - ps: Start-FileDownload 'http://leafo.net/dump/lua5_1_4_Win32_dll8_lib.zip'
  - 7z e lua5_1_4_Win32_dll8_lib.zip
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - dir .

build_script:
  - make
